// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fanfury/merkledrop/v1beta1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Indexes struct {
	MerkledropId uint64   `protobuf:"varint,1,opt,name=merkledrop_id,json=merkledropId,proto3" json:"merkledrop_id,omitempty" yaml:"mdi"`
	Index        []uint64 `protobuf:"varint,2,rep,packed,name=index,proto3" json:"index,omitempty" yaml:"i"`
}

func (m *Indexes) Reset()         { *m = Indexes{} }
func (m *Indexes) String() string { return proto.CompactTextString(m) }
func (*Indexes) ProtoMessage()    {}
func (*Indexes) Descriptor() ([]byte, []int) {
	return fileDescriptor_370bcafc752b09b2, []int{0}
}
func (m *Indexes) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Indexes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Indexes.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Indexes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Indexes.Merge(m, src)
}
func (m *Indexes) XXX_Size() int {
	return m.Size()
}
func (m *Indexes) XXX_DiscardUnknown() {
	xxx_messageInfo_Indexes.DiscardUnknown(m)
}

var xxx_messageInfo_Indexes proto.InternalMessageInfo

type GenesisState struct {
	LastMerkledropId uint64       `protobuf:"varint,1,opt,name=last_merkledrop_id,json=lastMerkledropId,proto3" json:"last_merkledrop_id,omitempty"`
	Merkledrops      []Merkledrop `protobuf:"bytes,2,rep,name=merkledrops,proto3" json:"merkledrops"`
	Indexes          []*Indexes   `protobuf:"bytes,3,rep,name=indexes,proto3" json:"indexes,omitempty"`
	Params           Params       `protobuf:"bytes,4,opt,name=params,proto3" json:"params"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_370bcafc752b09b2, []int{1}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Indexes)(nil), "fanfury.merkledrop.v1beta1.Indexes")
	proto.RegisterType((*GenesisState)(nil), "fanfury.merkledrop.v1beta1.GenesisState")
}

func init() {
	proto.RegisterFile("fanfury/merkledrop/v1beta1/genesis.proto", fileDescriptor_370bcafc752b09b2)
}

var fileDescriptor_370bcafc752b09b2 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xc1, 0x6a, 0xea, 0x40,
	0x18, 0x85, 0x13, 0xcd, 0xd5, 0xcb, 0xe8, 0xbd, 0x94, 0xd0, 0x45, 0x70, 0x31, 0x4a, 0x0a, 0x6d,
	0xa0, 0x25, 0x41, 0xdd, 0x15, 0x0a, 0x25, 0x9b, 0x22, 0xb4, 0xa5, 0xa4, 0xbb, 0x6e, 0x64, 0x62,
	0xc6, 0x38, 0xd4, 0x64, 0x42, 0x66, 0x2c, 0xfa, 0x10, 0x85, 0x3e, 0x96, 0x4b, 0x97, 0x5d, 0x49,
	0xab, 0x6f, 0xe0, 0x13, 0x14, 0x33, 0x63, 0x93, 0x45, 0x9b, 0xdd, 0xc0, 0xff, 0x9d, 0x73, 0xfe,
	0x39, 0x3f, 0xb0, 0xc6, 0x28, 0x1e, 0xcf, 0xd2, 0x85, 0x13, 0xe1, 0xf4, 0x79, 0x8a, 0x83, 0x94,
	0x26, 0xce, 0x4b, 0xd7, 0xc7, 0x1c, 0x75, 0x9d, 0x10, 0xc7, 0x98, 0x11, 0x66, 0x27, 0x29, 0xe5,
	0x54, 0x6f, 0x49, 0xd2, 0xce, 0x49, 0x5b, 0x92, 0xad, 0xe3, 0x90, 0x86, 0x34, 0xc3, 0x9c, 0xfd,
	0x4b, 0x28, 0x5a, 0x70, 0x44, 0x59, 0x44, 0x99, 0xe3, 0x23, 0x86, 0xbf, 0x4d, 0x47, 0x94, 0xc4,
	0x72, 0x7e, 0x5e, 0x92, 0x5d, 0x08, 0x11, 0xf0, 0x59, 0x09, 0x9c, 0xa0, 0x14, 0x45, 0x72, 0x4f,
	0xd3, 0x07, 0xf5, 0x41, 0x1c, 0xe0, 0x39, 0x66, 0x7a, 0x1f, 0xfc, 0xcb, 0xe9, 0x21, 0x09, 0x0c,
	0xb5, 0xa3, 0x5a, 0x9a, 0xfb, 0x7f, 0xb7, 0x6e, 0x83, 0x05, 0x8a, 0xa6, 0x97, 0x66, 0x14, 0x10,
	0xd3, 0x6b, 0xe6, 0xd0, 0x20, 0xd0, 0x4d, 0xf0, 0x87, 0xec, 0xf5, 0x46, 0xa5, 0x53, 0xb5, 0x34,
	0xb7, 0xb9, 0x5b, 0xb7, 0xff, 0x0a, 0x98, 0x98, 0x9e, 0x18, 0x99, 0xaf, 0x15, 0xd0, 0xbc, 0x11,
	0xed, 0x3c, 0x72, 0xc4, 0xb1, 0x7e, 0x01, 0xf4, 0x29, 0x62, 0x7c, 0xf8, 0x43, 0x9c, 0x77, 0xb4,
	0x9f, 0xdc, 0x15, 0x23, 0xee, 0x41, 0x23, 0x07, 0x59, 0x16, 0xd4, 0xe8, 0x9d, 0xda, 0xbf, 0x17,
	0x6c, 0xe7, 0x72, 0x57, 0x5b, 0xae, 0xdb, 0x8a, 0x57, 0x34, 0xd0, 0xaf, 0x40, 0x9d, 0x88, 0x2f,
	0x1b, 0xd5, 0xcc, 0xeb, 0xa4, 0xcc, 0x4b, 0xb6, 0xe3, 0x1d, 0x34, 0xfa, 0x35, 0xa8, 0x89, 0x06,
	0x0d, 0xad, 0xa3, 0x5a, 0x8d, 0x9e, 0x59, 0xa6, 0x7e, 0xc8, 0x48, 0xb9, 0x85, 0xd4, 0xb9, 0xb7,
	0xcb, 0x4f, 0xa8, 0x2c, 0x37, 0x50, 0x5d, 0x6d, 0xa0, 0xfa, 0xb1, 0x81, 0xea, 0xdb, 0x16, 0x2a,
	0xab, 0x2d, 0x54, 0xde, 0xb7, 0x50, 0x79, 0xb2, 0x43, 0xc2, 0x27, 0x33, 0xdf, 0x1e, 0xd1, 0xc8,
	0x89, 0x71, 0x32, 0x21, 0x29, 0x89, 0x9c, 0xc3, 0x39, 0xe7, 0xc5, 0x83, 0xf2, 0x45, 0x82, 0x99,
	0x5f, 0xcb, 0x0e, 0xd9, 0xff, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x37, 0xc0, 0x8a, 0xa6, 0x9c, 0x02,
	0x00, 0x00,
}

func (m *Indexes) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Indexes) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Indexes) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		dAtA2 := make([]byte, len(m.Index)*10)
		var j1 int
		for _, num := range m.Index {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintGenesis(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x12
	}
	if m.MerkledropId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MerkledropId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Indexes) > 0 {
		for iNdEx := len(m.Indexes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Indexes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Merkledrops) > 0 {
		for iNdEx := len(m.Merkledrops) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Merkledrops[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.LastMerkledropId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LastMerkledropId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Indexes) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MerkledropId != 0 {
		n += 1 + sovGenesis(uint64(m.MerkledropId))
	}
	if len(m.Index) > 0 {
		l = 0
		for _, e := range m.Index {
			l += sovGenesis(uint64(e))
		}
		n += 1 + sovGenesis(uint64(l)) + l
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LastMerkledropId != 0 {
		n += 1 + sovGenesis(uint64(m.LastMerkledropId))
	}
	if len(m.Merkledrops) > 0 {
		for _, e := range m.Merkledrops {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Indexes) > 0 {
		for _, e := range m.Indexes {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Indexes) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Indexes: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Indexes: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerkledropId", wireType)
			}
			m.MerkledropId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MerkledropId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGenesis
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Index = append(m.Index, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGenesis
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGenesis
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthGenesis
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Index) == 0 {
					m.Index = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenesis
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Index = append(m.Index, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastMerkledropId", wireType)
			}
			m.LastMerkledropId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastMerkledropId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Merkledrops", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Merkledrops = append(m.Merkledrops, Merkledrop{})
			if err := m.Merkledrops[len(m.Merkledrops)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Indexes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Indexes = append(m.Indexes, &Indexes{})
			if err := m.Indexes[len(m.Indexes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
